apiVersion: v1
kind: Service
metadata:
  name: folio-client-service
  labels:
    app: folio-client
spec:
  selector:
    app: folio-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP